#Implementation of LeNet Achitecture

The LeNet architecture is an excellent “first architecture” for Convolutional Neural Networks (especially when trained on the MNIST dataset, an image dataset for handwritten digit recognition).

LeNet is small and easy to understand — yet large enough to provide interesting results. Furthermore, the combination of LeNet + MNIST is able to run on the CPU, making it easy for beginners to take their first step in Deep Learning and Convolutional Neural Networks.

The LeNet architecture consists of the following layers:
INPUT => CONV => RELU => POOL => CONV => RELU => POOL => FC => RELU => FC

In [12]:
from sklearn.model_selection import train_test_split
from keras.datasets import mnist
from keras.optimizers import SGD
from keras.utils import np_utils
from keras import backend as K
import numpy as np
import argparse
import cv2

In [13]:
((trainData, trainLabels), (testData, testLabels)) = mnist.load_data()

In [14]:
trainData.shape

(60000, 28, 28)

In [15]:
testData.shape

(10000, 28, 28)

Each image is having dimension 28x28

In [16]:
# if we are using "channels first" ordering, then reshape the
# design matrix such that the matrix is:
# num_samples x depth x rows x columns
if K.image_data_format() == "channels_first":
	trainData = trainData.reshape((trainData.shape[0], 1, 28, 28))
	testData = testData.reshape((testData.shape[0], 1, 28, 28))
# otherwise, we are using "channels last" ordering, so the design
# matrix shape should be: num_samples x rows x columns x depth
else:
	trainData = trainData.reshape((trainData.shape[0], 28, 28, 1))
	testData = testData.reshape((testData.shape[0], 28, 28, 1))

In [17]:
# scale data to the range of [0, 1]
trainData = trainData.astype("float32") / 255.0
testData = testData.astype("float32") / 255.0

In [18]:
trainData.shape

(60000, 28, 28, 1)

In [19]:
# transform the training and testing labels into vectors in the
# range [0, classes] -- this generates a vector for each label,
# where the index of the label is set to `1` and all other entries
# to `0`; in the case of MNIST, there are 10 class labels
trainLabels = np_utils.to_categorical(trainLabels, 10)
testLabels = np_utils.to_categorical(testLabels, 10)

In [20]:
trainLabels[1]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [21]:
from keras.models import Sequential
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.layers.core import Activation
from keras.layers.core import Flatten
from keras.layers.core import Dense

In [22]:
model = Sequential()

model.add(Conv2D(20,5,padding='same',input_shape=(28,28,1)))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))
model.add(Conv2D(50,5, padding='same'))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))

model.add(Flatten())
model.add(Dense(500))
model.add(Activation('relu'))

#output layer
model.add(Dense(10))
model.add(Activation('softmax'))

model.compile(optimizer=SGD(lr=0.01), loss="categorical_crossentropy", metrics=['accuracy'])



In [23]:
model.fit(trainData, trainLabels, batch_size=128, epochs=20,
		verbose=1)

Epoch 1/20
469/469 [==============================] - 108s 228ms/step - loss: 1.5566 - accuracy: 0.6052
Epoch 2/20
469/469 [==============================] - 106s 225ms/step - loss: 0.2811 - accuracy: 0.9178
Epoch 3/20
469/469 [==============================] - 106s 226ms/step - loss: 0.1935 - accuracy: 0.9442
Epoch 4/20
469/469 [==============================] - 107s 228ms/step - loss: 0.1500 - accuracy: 0.9555
Epoch 5/20
469/469 [==============================] - 105s 223ms/step - loss: 0.1239 - accuracy: 0.9624
Epoch 6/20
469/469 [==============================] - 106s 227ms/step - loss: 0.1012 - accuracy: 0.9694
Epoch 7/20
469/469 [==============================] - 106s 227ms/step - loss: 0.0899 - accuracy: 0.9726
Epoch 8/20
469/469 [==============================] - 104s 223ms/step - loss: 0.0835 - accuracy: 0.9743
Epoch 9/20
469/469 [==============================] - 104s 221ms/step - loss: 0.0762 - accuracy: 0.9777
Epoch 10/20
469/469 [==============================] - 104s 222m

In [24]:
(loss, accuracy) = model.evaluate(testData, testLabels,
		batch_size=128, verbose=1)

79/79 [==============================] - 6s 68ms/step - loss: 0.0406 - accuracy: 0.9857


In [31]:
np.newaxis

In [35]:
probs = model.predict(testData[np.newaxis,0])
prediction = probs.argmax(axis=1)

In [37]:
prediction

array([7])

In [38]:
testLabels[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [34]:
testData[np.newaxis,0].shape

(1, 28, 28, 1)